var fs = require('fs');
var dir = 'C:/ws/java/roudan-jdbc-cli/readme';

var zh = '# roudan-jdbc-cli\n\n[English](../README.md) | [简体中文](README.zh.md) | [繁體中文](README.zht.md)\n\nJDBC CLI 工具，专为 AI agent 设计。可通过 JDBC 连接任何数据库执行 SQL，输出 JSON 到 stdout。\n\n## 一键激活\n\n复制这行粘贴到 OpenCode / Claude Code / Cursor：\n\n> Install and use roudan-jdbc-cli, a JDBC CLI that lets me execute SQL against any database:  \n> https://raw.githubusercontent.com/wsaaaqqq/roudan-jdbc-cli/main/INSTALL.md\n\n## 快速开始\n\n### 前置条件\n\n- **Java 8+** (JRE 或 JDK，需在 PATH 上) — 从 https://adoptium.net 安装\n- 数据库对应的 **JDBC 驱动 JAR**（MySQL, PostgreSQL, DM 等）\n\n### 安装\n\n```bash\nnpm install -g roudan-jdbc-cli    # 已内含 jar，安装即用\n\n# 或 Docker\ndocker pull wsaaaqqq/roudan-jdbc-cli\n\n# 或一行 curl 安装\ncurl -fsSL https://raw.githubusercontent.com/wsaaaqqq/roudan-jdbc-cli/main/install.sh | bash\n```\n\n### 使用\n\n```bash\n# ====== 连接持久化（一次登录，随处使用）======\n\nroudan -u jdbc:mysql://localhost:3306/test -n root -p pass -d com.mysql.cj.jdbc.Driver -j ./mysql-connector.jar login\nroudan login -f application-dm.yml -j DmJdbcDriver.jar\nroudan login -f multi.yml mydb\n\n# 登录后省略连接参数\nroudan test\nroudan tables\nroudan query -s "SELECT * FROM T_USER" --limit 5\nroudan use mydb\nroudan connections\nroudan logout\n\n# ====== 直连模式 ======\n\nroudan -u jdbc:mysql://localhost:3306/test -n root -p pass -d com.mysql.cj.jdbc.Driver -j ./mysql-connector.jar test\nroudan query -s "SELECT * FROM T_USER" --limit 5\nroudan query -s "SELECT * FROM T_USER WHERE id = :id" --named -a \'{"id":"U01"}\'\nroudan tables\nroudan describe -t T_USER\nroudan exec -f script.sql\n```\n\n## 命令\n\n| 命令 | 说明 |\n|------|------|\n| `login` | 保存连接（CLI 参数或 `-f yml`） |\n| `logout` | 清除当前连接 |\n| `use` | 切换到已保存的连接 |\n| `ls` | 列出已保存的连接及详情 |\n| `rename` | 重命名已保存的连接 |\n| `connections` | 列出所有已保存的连接 |\n| `query` | SELECT 查询 |\n| `count` | COUNT 查询 |\n| `modify` | INSERT/UPDATE/DELETE/DDL |\n| `tables` | 列出表/视图 |\n| `describe` | 查看表结构 |\n| `test` | 连接测试 |\n| `exec` | 执行 SQL 文件（单事务） |\n| `import` | 从 CSV/JSON 导入数据 |\n| `export` | 导出查询结果到 CSV/JSON |\n| `gen` | 生成 DDL 或 INSERT |\n| `tail` | 监控表变化 |\n| `begin` | 开始事务 |\n| `commit` | 提交事务 |\n| `rollback` | 回滚事务 |\n\n`login` 将连接保存到 `~/.roudan/connections.json`，之后无需重复传参。\n\n完整参考：[CLI_REFERENCE.md](../doc/CLI_REFERENCE.md)\n\n## License\n\nApache 2.0\n';

var zht = '# roudan-jdbc-cli\n\n[English](../README.md) | [簡體中文](README.zh.md) | [繁體中文](README.zht.md)\n\nJDBC CLI 工具，專為 AI agent 設計。可透過 JDBC 連接任何資料庫執行 SQL，輸出 JSON 到 stdout。\n\n## 一鍵啟動\n\n複製這行貼到 OpenCode / Claude Code / Cursor：\n\n> Install and use roudan-jdbc-cli, a JDBC CLI that lets me execute SQL against any database:  \n> https://raw.githubusercontent.com/wsaaaqqq/roudan-jdbc-cli/main/INSTALL.md\n\n## 快速開始\n\n### 前置條件\n\n- **Java 8+** (JRE 或 JDK，需在 PATH 上) — 從 https://adoptium.net 安裝\n- 資料庫對應的 **JDBC 驅動 JAR**（MySQL, PostgreSQL, DM 等）\n\n### 安裝\n\n```bash\nnpm install -g roudan-jdbc-cli    # 已內含 jar，安裝即用\n\n# 或 Docker\ndocker pull wsaaaqqq/roudan-jdbc-cli\n\n# 或一行 curl 安裝\ncurl -fsSL https://raw.githubusercontent.com/wsaaaqqq/roudan-jdbc-cli/main/install.sh | bash\n```\n\n### 使用\n\n```bash\n# ====== 連線持久化（一次登入，隨處使用）======\n\nroudan -u jdbc:mysql://localhost:3306/test -n root -p pass -d com.mysql.cj.jdbc.Driver -j ./mysql-connector.jar login\nroudan login -f application-dm.yml -j DmJdbcDriver.jar\nroudan login -f multi.yml mydb\n\n# 登入後省略連線參數\nroudan test\nroudan tables\nroudan query -s "SELECT * FROM T_USER" --limit 5\nroudan use mydb\nroudan connections\nroudan logout\n\n# ====== 直連模式 ======\n\nroudan -u jdbc:mysql://localhost:3306/test -n root -p pass -d com.mysql.cj.jdbc.Driver -j ./mysql-connector.jar test\nroudan query -s "SELECT * FROM T_USER" --limit 5\nroudan query -s "SELECT * FROM T_USER WHERE id = :id" --named -a \'{"id":"U01"}\'\nroudan tables\nroudan describe -t T_USER\nroudan exec -f script.sql\n```\n\n## 命令\n\n| 命令 | 說明 |\n|------|------|\n| `login` | 儲存連線（CLI 參數或 `-f yml`） |\n| `logout` | 清除當前連線 |\n| `use` | 切換到已儲存的連線 |\n| `ls` | 列出已儲存的連線及詳情 |\n| `rename` | 重新命名已儲存的連線 |\n| `connections` | 列出所有已儲存的連線 |\n| `query` | SELECT 查詢 |\n| `count` | COUNT 查詢 |\n| `modify` | INSERT/UPDATE/DELETE/DDL |\n| `tables` | 列出表/檢視 |\n| `describe` | 檢視表結構 |\n| `test` | 連線測試 |\n| `exec` | 執行 SQL 檔案（單交易） |\n| `import` | 從 CSV/JSON 匯入資料 |\n| `export` | 匯出查詢結果到 CSV/JSON |\n| `gen` | 生成 DDL 或 INSERT |\n| `tail` | 監控表變化 |\n| `begin` | 開始交易 |\n| `commit` | 提交交易 |\n| `rollback` | 回滾交易 |\n\n`login` 將連線儲存到 `~/.roudan/connections.json`，之後無需重複傳參。\n\n完整參考：[CLI_REFERENCE.md](../doc/CLI_REFERENCE.md)\n\n## License\n\nApache 2.0\n';

fs.writeFileSync(dir + '/README.zh.md', zh, 'utf8');
fs.writeFileSync(dir + '/README.zht.md', zht, 'utf8');
console.log('done');
