#!/bin/sh
DIR="$(dirname "$0")"
if [ -x "$DIR/jre8/bin/java" ]; then
    exec "$DIR/jre8/bin/java" -jar "$DIR/lib/roudan-jdbc-cli.jar" "$@"
else
    exec java -jar "$DIR/lib/roudan-jdbc-cli.jar" "$@"
fi
